### ISSUE TITLE
The translations on new versions are discontinued

### ISSUE THREAD

**Issue by JuanDani** [ingbrzy/MA-XML-6.0-SPANISH#41]
Toggles are not translated, and all the new features of the last rom releases also, so I think that Spanish project of translation is stopped.

**Comment by cpasmoi** [comment]
yea, totally outdated :D

**Comment by rpperezr** [comment]
I'll try to update the translation this week.

Enviado desde mi iPad

**Comment by JulioMC** [comment]
I´m on it but i need help to check some things.

I do not know if I'm translating lines that should not touch.

¿Can anyone check it?

**Comment by ingbrzy** [comment]
yes, seems fine.. good job...!

**Comment by HonzoNebro** [comment]
I'm willing to help but I don't know how to identify what files need a translation. Any tips?

**Comment by x1704e** [comment]
@ingbrzy Please add me as a contributor here so that I can help out a bit.

**Comment by elyorch76** [comment]
Some of us are working to update it. Please, open issues if you find mistakes or non translated strings
