### ISSUE TITLE
Agradecimientos y algunos errores

### ISSUE THREAD

**Issue by elyorch76** [ingbrzy/MA-XML-6.0-SPANISH#62]
Antes que nada felicidades y gracias al usuario que ha retomado con ganas las traducciones al español: JulioMC.

Si te parece te iré comentando cositas que veo:

-Widget del tiempo no está completamente traducido. Cuando entras a la aplicación sí. Pero en el widget por ejemplo aparece Clear. Y cuando entras ya pone Soleado. Por cierto, yo creo que Clear debería ser Despejado.

-Deslice hacia la derecha para abrir Mi Remote debería ser Deslice hacia la derecha para abrir Teléfono.

-Aún faltan cosas por traducir pero supongo que eso ya lo sabrás, has avanzado mucho, ánimo! ;-)

**Comment by JulioMC** [comment]
Muy buenas:

Lo del Widget del tiempo creo que ya está bien traducido, lo veremos en la próxima ROM que salga.

Sobre lo del Mi Remote no lo puedo comprobar ya que tengo un Redmi y no me sale esa opción pero... ¿Cuándo deslizas hacia la derecha se abre realmente el teléfono? Porque creo que lo del Mi Remote es una característica que tiene el Mi4 para utilizarlo como mando a distancia.

Los errores en las traducciones los iré puliendo según los descubra y en ratos libres.

Saludos!

**Comment by elyorch76** [comment]
Yo tengo un Redmi 2, y sí, cuando deslizas hacia la derecha se abre el teléfono

**Comment by elyorch76** [comment]
En la 5.5.8 sigue igual. Me gustaría ayudar con las traducciones, pero no sé exactamente cómo funciona esto.

**Comment by JulioMC** [comment]
Efectivamente no sigue sin salir traducido el widget del tiempo. Tengo que seguir investigando el por qué... Todo lo que vi en inglés y se podía traducir, lo traduje.

Aquí tienes un tutorial, hay que tener cuidado con las lineas que se traducen porque puedes dejar alguna aplicación inutilizable:

https://docs.google.com/document/d/1H8DoN6nnbsOGB_fauBiCcpyB4OAIEHjqEiJX322v45Y/edit#

Saludos!

**Comment by elyorch76** [comment]
Gracias, voy a ver si lo consigo. Para compararlo con los strings ingleses originales como lo haces? Lo comparas con https://github.com/Acid-miuipolskapl/v6-XML-Compare? Lo raro es que ahí aparecen carpetas por dispositivos, y en el español sólo tenemos una general

**Comment by JulioMC** [comment]
Efectivamente, yo utilizo el del HM2013023 que corresponde con el Redmi 1.

En español sólo hay una general que es la que sirve para todos los dispositivos.

Saludos!

**Comment by elyorch76** [comment]
No puedo hacer Sync con mis cambios, necesito pedir permiso?

**Comment by elyorch76** [comment]
Ya me los han dado. Cierro este issue y me pongo a curra ;)
