### ISSUE TITLE
Lista de bloqueo

### ISSUE THREAD

**Issue by TxarliR** [ingbrzy/MA-XML-6.0-SPANISH#64]
Con esta versión 5.5.15 os habeis lucido ;) Todo esta en perfecto castellano pero sin embargo cuando vas a bloquear a alguien el mensaje aparece en inglés. Si pudierais solventar eso que yo sepa no quedaria nada mas.

Gran trabajo ;)

**Comment by elyorch76** [comment]
Gracias de parte de todos, y gracias por reportar cosas que faltan. Estoy seguro de que hay muchas más. Ahora mismo arreglo eso ;-)

**Comment by JulioMC** [comment]
Muy buen trabajo el que estás haciendo "elyorch76" :dancer: 

Un saludo!

**Comment by elyorch76** [comment]
Gracias! Tú también!

**Comment by TxarliR** [comment]
cierro el tema?

**Comment by elyorch76** [comment]
Si consideras que está resuelto sí, gracias
