### ISSUE TITLE
Ajustes/Sonidos

### ISSUE THREAD

**Issue by Yanj96** [ingbrzy/MA-XML-6.0-SPANISH#67]
Mejoraria la traduccion si fuera "Sonido" en vez de "Sonidos"

**Comment by elyorch76** [comment]
Gracias por el consejo.

Hecho. Puedes cerrar la incidencia cuando suban la siguiente ROM y veas que ya está corregido.

**Comment by Yanj96** [comment]
Llevo la estabe asi que tardare un tiempo xD
