### ISSUE TITLE
Nombre de volumenes

### ISSUE THREAD

**Issue by Yanj96** [ingbrzy/MA-XML-6.0-SPANISH#68]
Otra sugerencia mas: actualmente al estar escuchando musica, viendo videos... etc, al aumentar/disminuir el volumen sale traducido como "Medios", en mi opinion quedaria mejor "Multimedia".

**Comment by elyorch76** [comment]
Gracias por el consejo.

Hecho. Puedes cerrar la incidencia cuando suban la siguiente ROM y veas que ya está corregido.
