### ISSUE TITLE
Paradas escuchando audio por auriculares

### ISSUE THREAD

**Issue by tarantiro** [ingbrzy/MA-XML-6.0-SPANISH#69]
Escuchando audio por los auriculares, al de un un rato, se para medio segundo, y se sigue escuchando , pero los botones de control remoto del auricular dejan de funcionar. Se reinicia el telefono y se soluciona. Pero al de una hora, mas o menos, se repite este fallo. Esto ocurre con auriculares de Xiaomi como de otras marcas. Desconozco si es un fallo de mi unidad, Redmi 2 de 2G, os en un bug. Gracias.

**Comment by elyorch76** [comment]
Aquí solo se solucionan temas relacionados con las traducciones. También te digo que yo tengo un Redmi 2 de 1G y no me pasa eso.

**Comment by tarantiro** [comment]
Ok. Sorry!!
