### ISSUE TITLE
MIUI 6 (6.6.1.0 KHCMICF) Redmi 1S: Ringtone selection "other" option disapeared

### ISSUE THREAD

**Issue by ilopez85** [ingbrzy/MA-XML-6.0-SPANISH#70]
https://github.com/BurgerZ/jBART/issues/99

MIUI 6 (6.6.1.0 KHCMICF) Redmi 1S: Ringtone selection "other" option under sound settings disapeared after translate the ROM to spanish language.

Before translate:
http://i.imgur.com/0RE9bda.png?1

After translate:
http://i.imgur.com/DfgcNOA.png?1

**Comment by elyorch76** [comment]
Those images are from the portuguese language, not spanish

**Comment by ilopez85** [comment]
I tried portuguese language after report the problem with spanish translation in jBART github because they told me that I tried it with another language (you can read the full conversation at: https://github.com/BurgerZ/jBART/issues/99)

**Comment by ilopez85** [comment]
I tried portuguese language after report the problem with spanish translation in jBART github because they told me that I tried it with another language (you can read the full conversation at: BurgerZ/jBART#99)

**Comment by elyorch76** [comment]
I can't see how this can be a problem with the translation. It's working fine for me, I have the weekly ROM. If it's working badly in more than one language must be a problem with the ROM.

**Comment by ilopez85** [comment]
I have contacted you because that is what they told me, but I also doubt that it will be translation problem.
Is there another way to translate the ROM than using jBART?

**Comment by elyorch76** [comment]
I dont know what jBART is. I simply use the ROMs already translated from 

http://xiaomi.eu/community/forums/miui-weekly-rom-releases.103/
