### ISSUE TITLE
Error in battery menu

### ISSUE THREAD

**Issue by MrFilippo** [ingbrzy/MA-XML-6.0-SPANISH#71]
There is a bug in version 7.5.26, section "battery saver". As you see in the image, the menu is misplaced and can not see other options should appear below. I think maybe is a translation error.

![image](https://cloud.githubusercontent.com/assets/13544037/8940853/67facc2a-356c-11e5-99ef-c48bf8f4fb29.png)

**Comment by elyorch76** [comment]
Si el error ha surgido con esta versión no es un error de traducción, porque hace meses que no toco la traducción de esta parte. Además de que no puedo ver que está mal en la traducción para que se muestre así

**Comment by MrFilippo** [comment]
Buenas noches,
gracias por responder y por tu trabajo.
Anteriormente tenía la versión estable miui 6.6.1.0 y no aparecía este error. Pensé que sería por la traducción o algo relacionado con el idioma español.

**Comment by danicbsn** [comment]
A mi me ha empezado a pasar en la 5.7.16. Volví a la 5.7.9 y se solucionó. Luego puse la 5.7.26 y vuelve el error. 
RedMi 1S

**Comment by danicbsn** [comment]
solucionado en la 5.7.31.
Gracias!

**Comment by MrFilippo** [comment]
Efectivamente, se ha solventado el problema con el segundo menú. Muchas gracias. 
Sin embargo, por lo menos en mi caso (Redmi 2) algunos menús y opciones que antes aparecían traducidos al castellano, ahora no lo están.
![screenshot_2015-08-01-10-40-24](https://cloud.githubusercontent.com/assets/13544037/9021263/f77de538-3839-11e5-958d-c5be0eb11d36.png)

**Comment by ingbrzy** [comment]
Your lang has too long translation.. Make it shorter...

**Comment by elyorch76** [comment]
I know, I'll fix it for the next rom

**Comment by MrFilippo** [comment]
Humildemente sugiero la siguiente traducción. I suggest the following translation
* "Perfiles de batería" ==> "Perfiles"
* "Battery Saver" ==> "Ahorrar"
* "At 15% battery switch to Ahorro" ==> "15% batería >> Ahorro"
* "Programar cambio de perfil" ==> "Cambio Perfil"
* "Desde 23:25 a 7:30 cambiar a Dormir" ==> "23:25 a 7:30 >> Dormir"
* "Programar encendido y apagado" ==> "Encender / Apagar" 
* "Power on tomorrow at 04:20" ==> "Encender 4:20"
* "El dispositivo se apagará a las 23:30" ==> "Apagar 23:30"
