### ISSUE TITLE
TAP TO REBOOT (or to SHUT DOWN)

### ISSUE THREAD

**Issue by phluimsa** [ingbrzy/MA-XML-6.0-SPANISH#72]
It's not translated to spanish...

Pulsar para reiniciar

Pulsar para apagar.

**Comment by elyorch76** [comment]
It is translated. Which version are you using? Which device?

**Comment by phluimsa** [comment]
Last version downloaded from XIAOMI.EU....
6.6.4.0 (KXDCNCF) Estable

Those messages are in english, but the other are in spanish.
I push the power button then REINICIAR or APAGAR and i get that message in english.
The phone is just wiped all.

**Comment by phluimsa** [comment]
In this thread can I write in spanish?

**Comment by elyorch76** [comment]
Sí, quizas hubo un problema al crear la versión estable. En la versión de desarrollo están traducidos.

**Comment by phluimsa** [comment]
Ok, perfecto, tanto en esta versión como en la de finales de julio estables, me salen en inglés, en mi Xiaomi Mi4 pero también lo he visto en el RedmiNote 4G dual sim  de un amigo y en el de 1 sim de mi hermana.
