### ISSUE TITLE
Texto incompleto al establecer el fondo

### ISSUE THREAD

**Issue by proudh0n** [ingbrzy/MA-XML-6.0-SPANISH#73]
A la hora de establecer el fondo, cuando permite decidir donde se va a cambiar el fondo el texto está incompleto. Es posible que no haya sitio para mostrarlo y por eso no se vea, mi dispositivo es un Redmi 2 con resolución 720. En ese caso sugiero cambiar los textos por "Bloqueo", "Inicio" y "Ambos", obviando el "Pantalla de". Adjunto captura.

![screenshot_2015-08-23-10-30-33](https://cloud.githubusercontent.com/assets/8055505/9427520/8fe6d18c-4982-11e5-8248-1218e920899c.png)

**Comment by elyorch76** [comment]
Gracias, lo corrijo

**Comment by elyorch76** [comment]
Corregido para la próxima versión

**Comment by proudh0n** [comment]
Gracias por tu trabajo :)

**Comment by elyorch76** [comment]
De nada! ;-)
