### ISSUE TITLE
Errores en traducción al español

### ISSUE THREAD

**Issue by jlmcr87** [ingbrzy/MA-XML-6.0-SPANISH#74]
Hola adjunto capturas de pantalla con todo lo que falta por traducir al español y que está en inglés o tiene algun defecto en un Xiaomi Redmi Note 2, rom de xiaomi.eu 5.9.2 beta. Espero ayudar. Gracias
1. En inglés: Los ajustes de APN no están disponibles para este usuario
![screenshot_2015-09-03-07-20-56](https://cloud.githubusercontent.com/assets/4967467/9651259/4ec871b2-520e-11e5-9bdf-134fd071f59c.png)
2. El nombre del SSID viene por defecto en chino, habría que cambiarlo en español.
![screenshot_2015-09-03-07-23-16](https://cloud.githubusercontent.com/assets/4967467/9651262/5492bb66-520e-11e5-876b-787c63fae247.png)
3. Falta una U mayúscula en "Usar modo lectura para las aplicaciones que elija"
![screenshot_2015-09-03-07-25-29](https://cloud.githubusercontent.com/assets/4967467/9651264/56853ef8-520e-11e5-94f8-a294631cd1c1.png)
4. En inglés: Auto-rotar pantalla
![screenshot_2015-09-03-07-25-48](https://cloud.githubusercontent.com/assets/4967467/9651266/597db888-520e-11e5-8ce5-dc06913b1dca.png)
5. Todos los menús de No molestar en inglés:
![screenshot_2015-09-03-07-27-35](https://cloud.githubusercontent.com/assets/4967467/9651267/5b83296a-520e-11e5-8004-3fae1e1ae828.png)
6. En inglés: Alarmas, Luz de notificación o como viene en otros teléfonos LED de notificaciones.
![screenshot_2015-09-03-07-27-45](https://cloud.githubusercontent.com/assets/4967467/9651269/5d512850-520e-11e5-8f9a-982e460c128e.png)
7. En inglés: Sonidos, llamadas:
![screenshot_2015-09-03-07-27-57](https://cloud.githubusercontent.com/assets/4967467/9651271/5f3b4218-520e-11e5-81be-efaafabb6a19.png)
8. En inglés: Acceso a notificaciones, Avanzado, Agentes de confianza: Para usarlo, debes establecer una pantalla de bloqueo, Aplicaciones con acceso de uso
![screenshot_2015-09-03-07-28-44](https://cloud.githubusercontent.com/assets/4967467/9651275/62dede98-520e-11e5-87b4-74fc29833f91.png)
9. En inglés: Gestionar el uso de batería de las aplicaciones, Ahorrar batería restringiendo los procesos en segundo plano, individualmente en cada aplicación, conexiones WLAN y datos, y GPS
![screenshot_2015-09-03-07-29-33](https://cloud.githubusercontent.com/assets/4967467/9651277/662eb9ec-520e-11e5-9943-98bc14433ace.png)
10. En inglés algunas opciones como Texto de alto contraste, Pantalla, inversión de color, (Experimental) Puede afectar al rendimiento
![screenshot_2015-09-03-07-30-37](https://cloud.githubusercontent.com/assets/4967467/9651278/6813e994-520e-11e5-88c4-44e203934dda.png)

Saludos!

**Comment by elyorch76** [comment]
Gracias por ser tan detallado! Te comento lo que ha podido hacer:

1. Corregido

2. No he encontrado cómo cambiarlo.

3. Corregido.

4. Hace tiempo que está traducido. A lo mejor aún no han puesto bien la traducción en el Redmi Note 2. En mi Redmi 2 sale bien.

5. Corregido.

6. Corregido.

7. Corregido.

8. Corregido.

9. Está traducido, pero a mí tampoco me sale bien en mi Redmi 2. No sé cuál es el problema.

10. Corregido.

**Comment by escaner** [comment]
Sobre el punto 9, si entras dentro de la opción se ve el texto en español. ¿Es posible que el texto esté repetido en dos sitios y sólo uno de ellos esté traducido?
Uso Redmi 1s con miui.eu 5.9.1 beta.

**Comment by elyorch76** [comment]
Gracias, ya lo sé y lo he buscado, pero no. Sólo hay un lugar donde se puede traducir, aunque aparezca en 2 pantallas diferentes.
