### ISSUE TITLE
Mas errores en traducción al español

### ISSUE THREAD

**Issue by jlmcr87** [ingbrzy/MA-XML-6.0-SPANISH#75]
Mas cosas que faltan por traducir:
1.Simular espacio de color: Activado o desactivado, usar nu player (y su descripción), Inhabilitar enrutamiento audio USB(así viene en mi nexus 5) (y su descripción)
![screenshot_2015-09-06-22-53-11](https://cloud.githubusercontent.com/assets/4967467/9706617/08e70264-54eb-11e5-9f49-aaabf3d0fac9.png)
2.Habilitar inspección de atributos de vista, habilitar registro Wi-Fi detallado, Transferencia total de WiFi a móvil, Permitir siempre búsquedas de Wi-Fi, tamaños del búfer de Logger.(así viene en mi nexus 5) 
![screenshot_2015-09-06-22-53-36](https://cloud.githubusercontent.com/assets/4967467/9706618/08fef55e-54eb-11e5-85ef-c7e55943510f.png)
3.Texto de alto contraste, inversión de color, correción de color.
![screenshot_2015-09-06-22-53-49](https://cloud.githubusercontent.com/assets/4967467/9706619/090f16f0-54eb-11e5-88e1-bc0e65207654.png)

**Comment by elyorch76** [comment]
Corregido

**Comment by elyorch76** [comment]
De nada ;-)
