### ISSUE TITLE
Propuestas de traducciones

### ISSUE THREAD

**Issue by escaner** [ingbrzy/MA-XML-6.0-SPANISH#76]
Muy buenas

En primer lugar me gustaría agradecer el esfuerzo de traducción que se realiza aquí.

Y en segundo, comento unas propuestas que tengo, de textos que no aparecen traducidos o bien tienen algún error o no quedan claros. Todo está sacado de un Redmi 1s con sistema de miui.eu 5.9.1 beta:

1.
Un par de faltas, lo correcto sería: "Elija **qué** pantalla se **mostrará** después de eliminar un mensaje"
Lo mismo: "Las notificaciones de los emails que llegan serán **silenciadas**"

![screenshot_2015-09-10-11-46-53](https://cloud.githubusercontent.com/assets/14215211/9817160/822976e8-58a1-11e5-917b-1de2a2205289.png)

2.
Home -> Yo yo traduciría como **Inicio**

![screenshot_2015-09-10-11-51-42](https://cloud.githubusercontent.com/assets/14215211/9817344/86238346-58a2-11e5-860e-2dadefc80994.png)

3.
En fotografía, "frame" se traduce como "fotograma". Marco de cámara  (Camera frame) -> **Fotograma** de la cámara

![screenshot_2015-09-10-12-04-18](https://cloud.githubusercontent.com/assets/14215211/9817400/e7fea1d6-58a2-11e5-8f69-507f55434040.png)

4.
Los modos de medición de luz se llamarían así en castellano:
**Promedio del fotograma**
**Ponderada al centro**
**Medición puntual**

![screenshot_2015-09-10-12-02-00](https://cloud.githubusercontent.com/assets/14215211/9817495/94fd83ac-58a3-11e5-856d-9d05c2051f89.png)

5.
CAF significa Continuous AutoFocus -> **Autofoco continuo**

![screenshot_2015-09-10-12-03-27](https://cloud.githubusercontent.com/assets/14215211/9817600/43f0d3d2-58a4-11e5-9ade-7023ac511c2e.png)

6.
En estos casos "Group" es verbo, no sustantivo. Thread es un hilo de conversación. Y "carrier" es el operador de telefonía.

Grupo por tiempo (Group by time) -> **Agrupar por tiempo**

Group messages that are received within a minute of each other into the same thread -> **Agrupar mensajes recibidos en menos de un minuto dentro del mismo hilo.**

Grupo portador mensajes (Group carrier messages) -> No sé si cabrá **Agrupar mensajes del operador**, si no se podría poner **Agrupar por operador**

Grupo notificaciones de su compañía en el mismo subproceso (Group notifications from your carrier into the same thread) -> **Agrupar notificaciones de su compañía en el mismo hilo**

El verbo check funciona distinto en inglés:
Comprobar SMS para OTP (Check SMS for OTP) -> **Comprobar OTP en SMS**

Sin traducir:
Show blocked SMS / Show blocked SMS in conversations list
**Mostrar SMS bloqueados** / **Mostrar los SMS bloqueados en la lista de conversaciones**

Lo de abajo, sin traducir:
**Para sincronizar los mensajes desde Mi Cloud, entra en tu cuenta Mi Account y activa "sincronizar SMS".**

![screenshot_2015-09-10-12-07-03](https://cloud.githubusercontent.com/assets/14215211/9817629/5e3a9d68-58a4-11e5-8af0-9d48e1090bce.png)

7.
Mostrar diálogo de renombrar archivo al finalizar una ¿? (no cabe)
(Name recordings manually) -> Yo pondría algo así como: **Renombar grabaciones al finalizar**

![screenshot_2015-09-10-12-11-30](https://cloud.githubusercontent.com/assets/14215211/9818003/6ce89e26-58a6-11e5-9eb2-609e825ecf4c.png)

8.
Imprimiendo (Printing) -> Se traduce como: **Impresión**
"Cloud Print" no estoy seguro de si falta por traducir o es el nombre del servicio, con lo que ya estaría bien.

![screenshot_2015-09-10-12-13-19](https://cloud.githubusercontent.com/assets/14215211/9818023/8dfa5bb8-58a6-11e5-9254-3dfcb3628290.png)

9.
Disponible en bloqueo de pantalla (Show on lock screen) -> **Disponible en pantalla de bloqueo**
Son cosas distintas :)

![screenshot_2015-09-10-12-16-27](https://cloud.githubusercontent.com/assets/14215211/9818110/09ea96de-58a7-11e5-996a-0af9d6469136.png)

10.
Set data limit for SIM 2 -> **Establecer límite de datos para SIM 2**

![screenshot_2015-09-10-12-26-24](https://cloud.githubusercontent.com/assets/14215211/9818123/248a6f32-58a7-11e5-8ae0-a03e2e24344a.png)

11.
Dial, Launcher, no estoy seguro si no están traducidos deliberadamente, pero los pongo por si acaso.
Dial como nombre existe en castellano, significando lo mismo, con lo que ya estaría bien. Como verbo sería Marcar
Launcher no existe, pero tampoco sé si hay un mobre extendido en castellano para esa aplicación.

![screenshot_2015-09-10-12-31-08](https://cloud.githubusercontent.com/assets/14215211/9818282/0e1ef5b4-58a8-11e5-99c0-9bfd816cd34d.png)

12.
Ringtone -> **Tono de llamada**

![screenshot_2015-09-10-12-36-26](https://cloud.githubusercontent.com/assets/14215211/9818432/d391a756-58a8-11e5-8999-d55dea49ea7d.png)

13.
Discrepancias en la nomenclatura entre SIM1 y SIM2:
"Importar desde SIM 1" vs "Importar desde la tarjeta SIM 2"
"Exportar a SIM 1" vs "Copiar a la segunda tarjeta SIM"
"Configurar SIM 1" vs "Configurar la tarjeta SIM 2"

![screenshot_2015-09-10-12-52-59](https://cloud.githubusercontent.com/assets/14215211/9818464/0a05dda2-58a9-11e5-8258-444cba769490.png)

![screenshot_2015-09-10-12-54-17](https://cloud.githubusercontent.com/assets/14215211/9818302/28007dae-58a8-11e5-8711-04b0ccc9cb9e.png)

14.
Exit / Allow -> **Salir** / **Permitir**

![screenshot_2015-09-10-19-40-43](https://cloud.githubusercontent.com/assets/14215211/9818529/630bd33e-58a9-11e5-8666-70a7b6a44b52.png)

15.
Dos versiones de mensajes de aviso al desactivar la tarjeta SIM:

**Dejar de usar tarjeta SIM**
**Quizás no se puedan realizar llamadas o utilizar la conexión de datos móviles. ¿Dejar de usar la tarjeta SIM _nombre_?

**Dejar de usar tarjeta SIM**
**Esta tarjeta está configurada como SIM por defecto. Si deja(s) de usarla, no podrá(s) realizar llamadas o utilizar la conexión de datos móviles. Puede(s) desactivar esta tarjeta tras configurar otra SIM como tarjeta por defecto.**
Quedaría algo así, según sea tratamiento de tú o de usted

![screenshot_2015-09-10-22-21-25](https://cloud.githubusercontent.com/assets/14215211/9818599/b7219a62-58a9-11e5-9cf3-0ad0b4c9d158.png)

![screenshot_2015-09-11-12-16-49](https://cloud.githubusercontent.com/assets/14215211/9818605/bdc80fa4-58a9-11e5-8cb0-07cbcb145fcb.png)

16.
Falta traducir los valores de este campo: Inmediatamente, 1 minuto, 2 minutos...

![screenshot_2015-09-11-13-32-13](https://cloud.githubusercontent.com/assets/14215211/9819160/ae1ba6ee-58ac-11e5-965b-f900b63419ee.png)

**Comment by elyorch76** [comment]
Muchas gracias por tus comentarios y tu detalle!

1. Corregido
2. De momento lo vamos a dejar así, hay gente que prefiere Home a Inicio. No estamos muy seguros.
3. Yo creo que en este caso se refiere al formato. Lo he traducido como Formato de cámara.
4. Corregido.
5. Corregido.
6. Corregido.
7. Corregido.
8. Corregido. Es el nombre del servicio.
9. Considero que es correcto.
10.Corregido.
11.Launcher no está traducido a propósito.
12.Corregido.
13.Corregido.
14.Corregido.
15.Corregido.
16.Corregido.
