### ISSUE TITLE
Más cosas que faltan por traducir:

### ISSUE THREAD

**Issue by jlmcr87** [ingbrzy/MA-XML-6.0-SPANISH#77]
Xiaomi redmi note 2, versión 5.9.11:
1: El modo no molestar está completamente en inglés:
![screenshot_2015-09-11-23-10-05](https://cloud.githubusercontent.com/assets/4967467/9826533/6386ed80-58db-11e5-81f4-6d39fbdf695d.png)
2: Administrar el uso de batería de las aplicaciones (y su descripción)
![screenshot_2015-09-11-23-10-37](https://cloud.githubusercontent.com/assets/4967467/9826532/63866b3a-58db-11e5-9418-1598ac7c6d09.png)
3: Buffer de 256kb por log? 
![screenshot_2015-09-11-23-12-18](https://cloud.githubusercontent.com/assets/4967467/9826531/63866d56-58db-11e5-9feb-5291c8df4fdd.png)

**Comment by elyorch76** [comment]
1. Ya reportado
2. Ya reportado
3. Corregido
