### ISSUE TITLE
Modo no molestar sigue en inglés

### ISSUE THREAD

**Issue by jlmcr87** [ingbrzy/MA-XML-6.0-SPANISH#78]
Perdona que abra esto por tercera vez pero en ajustes--> no molestar sigue todo en inglés. Las otras dos veces me pusiste corregido pero sigue mal. El modelo de teléfono es xiaomi redmi note 2. Gracias.

![screenshot_2015-09-11-23-10-05](https://cloud.githubusercontent.com/assets/4967467/9826533/6386ed80-58db-11e5-81f4-6d39fbdf695d.png)

**Comment by elyorch76** [comment]
Corregido, encontré los problemas específicos del Redmi note 2
