### ISSUE TITLE
Redmi note 2   5.10.16

### ISSUE THREAD

**Issue by jlmcr87** [ingbrzy/MA-XML-6.0-SPANISH#84]
Queda todavía en inglés:

1.Desde hace dos versiones en ajustes sonido y vibración está en inglés.
![screenshot_2015-10-17-09-02-16_com android settings](https://cloud.githubusercontent.com/assets/4967467/10557481/f402c4ee-74ae-11e5-979e-6ba1224a99b0.png)

2.En opciones de pantalla de bloqueo: wake lock screen for notifications.
![screenshot_2015-10-17-09-04-31_com android settings](https://cloud.githubusercontent.com/assets/4967467/10557487/2c7b729e-74af-11e5-9d99-61c5c583236f.png)

3.En idioma y entrada: Voice input: Entrada de voz
![screenshot_2015-10-17-09-05-05_com android settings](https://cloud.githubusercontent.com/assets/4967467/10557491/403f7fa0-74af-11e5-87f6-e655776e6e2a.png)

4.Como ya he reportado muchas veces el modo don´t disturb sigue en inglés. No se si hay algún problema y no podeis.
Se podría traducir igual que en los nexus: Nada, Prioridad y Todo.
![screenshot_2015-10-17-09-02-39_com android settings](https://cloud.githubusercontent.com/assets/4967467/10557493/59262be0-74af-11e5-8dc9-62b158ae698e.png)

**Comment by elyorch76** [comment]
Todo corregido, encontré los problemas específicos del Redmi note 2

**Comment by jlmcr87** [comment]
Muchas gracias por tu trabajo!
