### ISSUE TITLE
Traducir  "Sound & vibration" (Ajustes) Redmi note 2

### ISSUE THREAD

**Issue by marcosmanteca** [ingbrzy/MA-XML-6.0-SPANISH#85]
Hola, en la versión 5.10.16 HERMES falta de traducir al Español el nombre del apartado "Sound & vibration" en "Ajustes". Le mando una captura. Muchas gracias por el trabajo que realiza para ayudar a la comunidad. Un saludo

![screenshot_2015-10-17-21-23-28_com android settings](https://cloud.githubusercontent.com/assets/11967463/10560794/41dd0e7e-7516-11e5-8bd1-f3e075eaff72.png)

**Comment by elyorch76** [comment]
Ya está traducido para la próxima versión

**Comment by marcosmanteca** [comment]
gracias amigo
