### ISSUE TITLE
Error 'Signature verification failed' al instalar rom en Redmi Note 2 Prime

### ISSUE THREAD

**Issue by Thorstorm** [ingbrzy/MA-XML-6.0-SPANISH#86]
Al intentar instalar la rom *xiaomi.eu_multi_hermes_5.10.16_v7-5.0.zip* desde el recovery siempre me devuelve el error de *Signature verification failed*. Por lo visto hay más gente experimentando este problema: http://54.243.194.135/thread-173076-1-1.html

**Comment by elyorch76** [comment]
Esto es sólo para errores de traducciones. Para ese tipo de cosas coméntalo directamente en el foro.
