### ISSUE TITLE
Traducciones que faltan

### ISSUE THREAD

**Issue by proudh0n** [ingbrzy/MA-XML-6.0-SPANISH#87]
![screenshot_2015-10-21-00-27-52_com android settings](https://cloud.githubusercontent.com/assets/8055505/10622938/e6d4fcc2-778a-11e5-90df-5285717958b6.png)
Revisando los ajustes de la última versión he encontrado algunos Strings sin traducir, os adjunto capturas:

![screenshot_2015-10-16-18-27-21_com android settings](https://cloud.githubusercontent.com/assets/8055505/10622854/50042200-778a-11e5-9056-69da0f45dcb0.png)

![screenshot_2015-10-16-18-27-31_com miui powerkeeper](https://cloud.githubusercontent.com/assets/8055505/10622856/548951d8-778a-11e5-9c5e-e77c8f0a6fca.png)

Muchas gracias por vuestro trabajo!

Edito para añadir que se trata del Redmi 2 con MIUI 5.10.15

**Comment by elyorch76** [comment]
Corregido

**Comment by proudh0n** [comment]
Muchas gracias por tu trabajo
