### ISSUE TITLE
Redmi Note 2- Correcciones

### ISSUE THREAD

**Issue by marcosmanteca** [ingbrzy/MA-XML-6.0-SPANISH#89]
Buenas ante todo gracias por tu trabajo.

Un detalle en la app "Actualización" al dar en opciones, aparece "Reiniciar a modo Recovery" no quedaría mejor: "Reiniciar en modo Recovery". Es solo un apunte.
 
![screenshot_2015-11-06-17-36-47_com android updater](https://cloud.githubusercontent.com/assets/11967463/11002604/1ec88560-84ae-11e5-99a2-19da9633ad65.png)

Otra cosa es en la app de Mensajes señalo lo que falta de traducir.

![screenshot_2015-11-06-17-37-22_com android mms](https://cloud.githubusercontent.com/assets/11967463/11002693/b7ef2988-84ae-11e5-89e1-29abfcc4ab11.png)

Muchas gracias por vuestro trabajo, si no fuera por vosotros tendríamos las roms en "Chinatown". Un saludo.

**Comment by elyorch76** [comment]
Todo corregido para la próxima versión. Gracias
